### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [aweinstock314/power#2]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by aweinstock314** [comment]
I'm using serialize for the FromHex/ToHex traits. The `hex` crate doesn't provide any implementations for ToHex, and provides a less useful/general FromHex impl than `rustc-serialize`. I just looked around for equivalents, and it seems like `rustc-hex` was published yesterday and is quasi-official, so I'm guessing other people were blocked from dropping `rustc-serialize` by the same issue. I'll upgrade when I find the time.
